### ISSUE TITLE
revisionDesc @status

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#1024]
183 persons records have `<revisionDesc status="uncorrected-draft">`. 

We currently only allow: "draft", "incomplete", "published" or "underReview". We define "underReview" as "Indicates that this document is under review by one or more editors." 

Do we need both "underReview" and "uncorrected-draft". If so, how would we define "uncorrected-draft".

**Comment by wlpotter** [comment]
For some context on "uncorrected-draft". We used this a few years ago when we moved all records that were on the dev branch (persons, places, and works, and maybe bibls) to production. The `//revisionDesc/@status` of "uncorrected-draft" was used to mark those records that we migrated from dev but did not review by hand. We did not want to lose this distinction by marking them as "draft", since this was potentially already in use on the production branch.

FWIW we are also planning to use this term in the Caesarea Testimonia database for records which were created by our undergraduate RAs from other electronic sources (e.g., Perseus, OCRd PDFs on HathiTrust, etc.) that the editors did not review.

**Comment by dlschwartz** [comment]
@wlpotter Thanks, that's helpful context. The schema work I'm doing requires a description for these kinds of attribute values (they are useful for encoding and documentation). Do we have a definition of "uncorrected-draft" that differs in meaningful ways from "underReview" which we currently describe as "Indicates that this document is under review by one or more editors"?

We should definitely use both if they have either a different meaning or require a different kind of review. But if there isn't much of a distinction we should collapse these two categories into one.

**Comment by dlschwartz** [comment]
Change from "underReview" to "uncorrected-draft"

https://github.com/srophe/srophe-app-data/commit/0d01d33db4a14a0f4eab425fb1f439d30ecb69c8
