### ISSUE TITLE
disambiguation

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#1030]
We currently have two significantly different ways of handling disambiguation between entities.

Places uses:
- `<note type="disambiguation">` with a prose statement that two entities are not the same. [Example](https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/114.xml#L137).
- `<relation name="share-a-name">` [Example](https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/114.xml#L171).

Persons uses: 
- `<relation type="disambiguation" name="different-from">`. This can take a tei:desc element with a prose description. [Example](https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/1057.xml#L202).
     - Sometimes there is no `type="disambiguation"`.
- `<relation name="possibly-identical">`. This can also take a tei:desc. [Example](https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/1057.xml#L208).

We don't have to handle things consistently across datasets but it seems preferable whenever possible.

**Comment by davidamichelson** [comment]
I think we would want to move towards imitating Places in almost all cases
that we can. Let's discuss.

**Comment by davidamichelson** [comment]
@wlpotter it seems that perhaps on this case we should move Places toward conforming with Persons. In other words change the note/@type="disambiguation" in Persons to relation type="disambiguation" name="different-from"

Thoughts?

This would change this below:
Disambiguation using note/@type="disambiguation" (optional)

If the encoder knows that two place entries which otherwise looks similar (for example due to a shared unusual name) are distinct, it is useful to insert a disambiguation note asserting this fact, to prevent the two places from being erroneously merged. It is far easier to prevent a merge of records than to undo one. A <note type="disambiguation"> may be inserted, preferably containing a link to the URI of the other place which is known to be different. For example:

<note type="disambiguation">
       Not the same place as 
       <placeName ref="http://syriaca.org/place/2532">Baqufa</placeName>.
</note>

If a particular source distinguishes between two places, it is useful to cite it in an @source.

**Comment by wlpotter** [comment]
@davidamichelson @dlschwartz Yes, I'm definitely in favor of moving from a `note[@type="disambiguation"]` to a tei:relation in places.

I suppose it's fine to keep the disambiguation notes, but it seems like the same thing can be accomplished using a `/relation/desc` element:

(this would be in place 298):
```
<relation type="disambiguation" name="different-from" mutual="http://syriaca.org/place/298 http://syriaca.org/place/2532">
  <desc>Not the same place as <placeName ref="http://syriaca.org/place/2532">Baqufa</placeName>.</desc>
</relation>
```

This seems more RDF-ready?

----

It does seem like there's a bit more normalization that needs to happen in tei:relation elements in general, but I'm assuming @dlschwartz we will make separate issues for those as you get through the validation errors?

**Comment by wlpotter** [comment]
Just recording this here from our last meeting. I believe we decided to move the information in these disambiguation notes to the `//revisionDesc/change` to make sure we record the data errors and fixes in the change log, but we can delete the tei:note elements themselves as they are not helpful to users, and would potentially confuse them

**Comment by dlschwartz** [comment]
Thanks for documenting Will
