### ISSUE TITLE
Authors headwords to EN from GEDSH

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#184]
@nathangibson So a search shows that there are 290 non-saints who have a name marked @syriaca-tags="#syriaca-anglicized" I would assume, I think that we could just move the head word to these? What do you think?

**Comment by nathangibson** [comment]
I think this is probably the best option we have, but I think we should review these headwords before release. This is because almost all of the "#syriaca-anglicized" names for the authors set were machine-generated by assigning English given name equivalents to all matching transliterated names. The potential issues are
 1. There are some "anglicized" versions that do not reflect what the person is normally called: e.g., "Isaac ibn Ḥunayn" for Isḥāq ibn Ḥunayn (person/1000). (We should probably discuss whether names of Arabic origin should have a different headword policy.) 
 2. The addName name parts might not be sufficiently anglicized in the "#syriaca-anglicized" names. 

However, I think this is better than our other options, because our other consistent sources for anglicized names are the translation of Barsoum, which can be funky, or CBSC, which is inconsistent.
