### ISSUE TITLE
John the Siloitus

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#416]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1824

I liked learning a new word, but I wonder if we should go with the less formal well-dweller?
On the other hand I am happy to defer to you JN if this is the technical term we should use.

**Comment by jsaintlauren** [comment]
We will keep siloitus since that is how he is known in other traditions too.

**Comment by davidamichelson** [comment]
Sounds good to me. One more question, is the spelling correct? A google search does not turn up any results.

**Comment by jsaintlauren** [comment]
Ah yes! OK -- good point.  The french have translated  the Syriac Biroh
(meaning pit or well) as silo.  But I think of silos as being in the air up
high- originally they were pits for storing things.  Anyhow the intro for
the hagiography by Nau was really entertaining.  He contrasts monks who
live in pit with stylites.  Matt suggested "bunker" as a translation.  I
think what is meant is a fortified pit rather than a well (usually we see
the word "gubo" for a well).
So silioite is to contrast with stylite.  We could call him John the
Silo-dweller ..
