### ISSUE TITLE
new Q entries from BHSE 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#535]
@davidamichelson @nathangibson  - are we going to create new records for the saints in the BHSE that are not in Qadishe? I think Dave that you had said at one point that this would be done?  

Here is an example: 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1856 

or Bar Hebraeus 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1826 
(there is a cult of Bar Hebraeus! So cool, right?!)

**Comment by nathangibson** [comment]
Hmm, for these records, the issue is that we have records for the person but do not have them linked together. See http://wwwb.library.vanderbilt.edu/person/1622 and http://wwwb.library.vanderbilt.edu/person/239. 
This relates to the two following issues, the first of which was already done: 
https://github.com/srophe/srophe-app-data/issues/329
https://github.com/srophe/srophe-app-data/issues/136

**Comment by nathangibson** [comment]
@jsaintlauren Are there others for which we don't have a person record at all?

**Comment by jsaintlauren** [comment]
Unfortunately there are.. example
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1856

**Comment by nathangibson** [comment]
This example is the one I'm saying _does_ have a person record: http://wwwb.library.vanderbilt.edu/person/1622 -- it just isn't linked. Is there another example we can look at?

**Comment by jsaintlauren** [comment]
OH! I see.  I am sorry.  Then maybe (happily!) I was wrong.
They might just need to be linked, then!
