### ISSUE TITLE
b. vs. ibn

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#579]
Gedsh usually uses b. instead of ibn, but here they did the opposite.

@nathangibson which should I use?

<idno>http://syriaca.org/person/1000</idno>
                <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1000-3" xml:lang="en"
                    resp="http://syriaca.org" syriaca-tags="#syriaca-headword">
                    <forename sort="1">Isaac</forename>
                    <addName type="family" sort="2">ibn Hunayn</addName>
                </persName>
                <persName>GEDSH:</persName>
                <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1000-1"
                    xml:lang="en-x-gedsh" source="#bib1000-1">
                    <forename sort="1">Isḥāq</forename>
                    <addName type="family" sort="2">ibn Ḥunayn</addName>
                </persName>

**Comment by nathangibson** [comment]
It really doesn't matter. If you're asking about this case in particular, I'd say it's just an inconsistency in GEDSH and we should do the same as we do with other headwords. If you're asking what our general policy should be, I would have a slight preference for spelling out "ibn" for the sake of the non-Arabic speakers, but only if it doesn't require an overhaul of our data. (And it'd be worth checking library cataloging standards.)

**Comment by davidamichelson** [comment]
Okay, I have it as ibn, but it should be easy to change.

**Comment by davidamichelson** [comment]
it should be lower case though correct?

**Comment by tacarlson** [comment]
It should only be capitalized if the person in question was known as "Ibn so-and-so" (e.g. Ibn Battuta, whose father's name was not Battuta).  Keeping GEDSH's inconsistency is fine, but as a general policy I'd encourage you to consider using "b." as Islamicists do (and "bt." for daughters) because it avoids the issues of alternate spellings, as people might search for "bin," "ben" (Hebrew and colloquial Arabic), "ebn" (colloquial Arabic and Persian, also French transcription of Arabic), and it also works for "bar" so that you don't need to decide whether to represent this person's relationship with his father in Arabic or in Syriac.  Islamicists generally use "b." for simplicity.

________________________________

**Comment by davidamichelson** [comment]
This is very compelling and since I already normalized the data to b., let's leave it at that.
Thanks @tacarlson!
