### ISSUE TITLE
Handling of Desc and Note for Abstracts and also the xml-ID

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#749]
We should make the following changes to all data:

TEI:desc in Place records, will become a TEI:note @type="description" and if the note is an abstract it will also have @subtype="abstract"

All such notes should have an @xml:Lang attribute with their language.

There should not be more than one abstract per language. Abstract is used to display a short description in search/browse result lists.

The current data will need to have its XML:IDs changes to the style description[recordnumber]-[description number]: eg. "description78-1"

Additional issues needed:
Change Gazetteer data for Desc elements and xml:IDs and attributes
Change other modules for XML:IDs and attributes
Winona will need to change paths where the app grabs the abstract (based on @subtype="abstract" instead of the string in the XML:ID) and also the grouping by TEI:note/@description to group them all together in the HTML

Work records will also need cleaning up and modelling in this way too.

**Comment by dlschwartz** [comment]
@davidamichelson I'm already a bit fuzzy on the details regarding what we decided here. From the perspective of schema writing, I want to make everything consistent across as many modules as possible.

All abstracts will look like this: 
`<note type="description" subtype="abstract" xml:id="description##-#" xml:lang="en/syr/etc.">`

Am I right about the following:
A subtype="abstract" can only go on a note type="description"
Every record must have one note subtype="abstract" xml:lang="en"
No record may have more than one note subtype="abstract" with the same xml:lang?

Question:
Are we sure we want xml:id="description"? The current list of note types is semi-open (meaning the schema suggests these values but does not require the encoder to use them): description, disambiguation, content, scope, incipit, explicit, prologue, filiation, incerta, errata, corrigenda, record-description, deprecation, misc. Sure we don't want different xml:ids for each of these, do we? If all notes require xml:ids we should use xml:id="note##-#". If only type="description" notes need xml:ids then the above would be fine but I'm not clear on why we would id some but not all of the notes. Ideas? Thoughts?





This would replace the following in persons:
`<note type="abstract" xml:id="abstract-en-#">`

**Comment by dlschwartz** [comment]
@davidamichelson Now I'm really annoyed. It turns out that TEI makes this really difficult. Note and desc elements are handled very differently inside the person and place elements. TEI allows the note element all over the place inside the person element but restricts its location inside the place element. Desc is not allowed anywhere inside person. 

As best I can tell, TEI allows a group of elements under the place element that deal with the place (placeName, location, terrain, country, etc.) followed by a group of elements that document the place (idno, bibl, note, link). Once you introduce a 'documentation' element you cannot have any additional elements about the place.

While the person element cannot take a desc element, a note element can appear anywhere inside a person element. It doesn't need to appear alongside other notes and doesn't need to appear at the end like the group of documentation elements mentioned above. 

I can't really figure out the logic of why TEI handles place and person so differently. But this difference must have driven the decision to use the desc element for abstracts in place records and the note element for abstracts in person records.

Based on all of this, I would suggest the following:
We should have a better xml:id and type attribute for abstracts. 
Keep note type="abstract" in persons but change the xml:id to abstract##-# and require an xml:lang
Keep the use of desc and note as they were in places. Add a type="abstract" and xml:id="abstract##-#" and require an xml:lang on all desc elements (which seems to be current practice anyway). 

`<note type="abstract" xml:id="abstract-en-13">` becomes `<note type="abstract" xml:id="abstract13-1" xml:lang="en">`

`<desc xml:id="abstract-en-78" xml:lang="en">` becomes `<desc type="abstract" xml:id="abstract78-1" xml:lang="en">`

**Comment by dlschwartz** [comment]
Dave and I are agreed that this is the proper way to encode abstracts.

**Comment by davidamichelson** [comment]
Okay here is the back story related to #747

**Comment by davidamichelson** [comment]
@dlschwartz I think we can retire these two issues but want to check in first.

**Comment by dlschwartz** [comment]
@davidamichelson I think we're good on this.

**Comment by dlschwartz** [comment]
@davidamichelson `<person>` can contain `<note>` but not `<desc>` while `<place>` can contain both`<note>` and `<desc>`. We have both in places currently. TEI restricts where note can appear in place as well (see above). I propose we keep this the way it is rather than try to bring abstracts into line across datasets.
