### ISSUE TITLE
namespaces on non-TEI attributes

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#765]
@davidamichelson @wsalesky Georg Vogeler strongly recommended that we use a syriaca namespace in cases where we've created an attribute in our customization.  Should we change syriaca-computed-start, syriaca-computed-end and syriaca-tags to "syriaca:computed-start", etc. We would also need to declare syriaca as a namespace in all of our documents and update schema and documentation. Thoughts?

**Comment by davidamichelson** [comment]
Yes we want to do this.

**Comment by wlpotter** [comment]
FYI, For BQG we updated this to a srophe namespace (see https://github.com/srophe/bethqatraye-data/issues/40). For example, the `@srophe:tags="#headword"` attribute here: https://github.com/srophe/bethqatraye-data/blob/master/data/places/tei/105.xml#L113.

We declared this namespace on the root element of these records as follows, `xmlns:srophe="https://srophe.app"`.

**Comment by wlpotter** [comment]
I have added the srophe namespace to the root element and changed `@syriaca-tags` to `@srophe:tags`.

We still need to change:
- syriaca-computed-start
- syriaca-computed-end

What should these be changed to? `srophe:computed-start` and `srophe:computed-end`?

**Comment by davidamichelson** [comment]
Need to add 
    srophe-computed-start
    srophe-computed-end
to the documentation

**Comment by wlpotter** [comment]
The data in places has been updated; leaving open until documentation change has been made.

**Comment by davidamichelson** [comment]
@dlschwartz  Would you look this over please and let me know if what I say matches the schema. Also see a couple of questions below.

## Namespace Declaration of Srophé App Attributes
_The Syriac Gazetteer_ is deployed using a customization of the Srophé App (https://srophe.app). The Srophé App includes a few modifications of the TEI schema to create new attributes specific to the domains of digital cultural heritage or Syriac Studies. Following the recommendations of section [23.3.2](https://tei-c.org/release/doc/tei-p5-doc/en/html/USE.html#MDNS) of the TEI P5 guidelines, these non-TEI attributes are attached to the https://srophe.app namespace in a namespace declaration in the TEI:header. Specifically, this namespaces is declared in the `<TEI>` root element as an alternate (not default) namespace.

Here is an example:
```
<TEI
	xml:lang="en"
	xmlns="http://www.tei-c.org/ns/1.0"
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:svg="http://www.w3.org/2000/svg"
	xmlns:math="http://www.w3.org/1998/Math/MathML"
	xmlns:srophe="https://srophe.app">
   <teiHeader>
```

At present there are three attributes attached to the https://srophe.app namespace. They are:
* @srophe:tags
* @srophe:computed-start
* @srophe:computed-end

**Comment by davidamichelson** [comment]
Please also check this:

### `<classDesc>`
The class declaration contains one or more taxonomies defining any classificatory codes used elsewhere in the text. There are various @srophe:tags values which Syriaca.org uses to mark elements for a variety of purposes.   Syriaca.org’s preferred name forms are tagged with "syriaca-headword", for example.  These tags are represented by `<category>` elements within a `<taxonomy>` element within a `<classDecl>` element after the `<editorialDecl>` element within the `<encodingDesc>`.  Each `<category>` has an @xml:id attribute whose value is the tag.  Within the `<category>` element is a `<catDesc>` element which contains a brief prose description of the category’s purpose.
	For example, the encoding of "syriaca-headword" might look as follows:

```
<classDecl>
	<taxonomy>
		<category xml:id="syriaca-headword">
			<catDesc>The name used by Syriaca.org for document titles, citation, and disambiguation. These names have been created according to the Syriac.org guidelines for headwords: <ref target="http://syriaca.org/documentation/headwords.html">http://syriaca.org/documentation/headwords.html</ref>.</catDesc>
		</category>
	</taxonomy>
</classDecl>
```

**Comment by davidamichelson** [comment]
Also do we use all of these namespaces:

xmlns="http://www.tei-c.org/ns/1.0"
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:svg="http://www.w3.org/2000/svg"
	xmlns:math="http://www.w3.org/1998/Math/MathML"
	xmlns:srophe="https://srophe.app"

**Comment by davidamichelson** [comment]
Please read this over too:

#### @srophe:computed-start & @srophe:computed-end
As evident from the examples above ancient and medieval chronological data can often be imprecise in terms of dates. It is quite common for an historical source to indicate only the year of an event rather than a specific month or day. The Srophé App has several tools and functions for sorting data by date, such as a timeline function. For these functions to calculate a date range, however, it is necessary to provide an ISO month and day even when one is not known. Accordingly, Syriaca.org has established a two-part encoding process to both maintain the original imprecision of the source (i.e no date, no month) and to also provide the Srophé App with precise dates that can be used for calculations. The encoding policy is as follows. All dates should be encoded with only the precision available from the historical sources following the patterns above. After this data has been entered but before finalization of the xml file, a data maintenance script is run on the data to create a second set of date encodings uinsg the @srophe:computed-start and @srophe:computed-end attributes attached to the https://srophe.app namespace. These encodings are always machine-generated and updated and should not be encoded by hand. The result (based on the example above from Karka d-Ledan (place/656)) is:

```
<state type="existence" from="0410" to="0605" srophe:computed-end="0605-01-01" srophe:computed-start="0410-01-01">
	<precision match="@from" notAfter="0410" srophe:computed-end="0410-01-01"/>
	<precision match="@to" notBefore="0605" srophe:computed-start="0605-01-01"/>
</state>
```
The values provided in @srophe:computed-start and @srophe:computed-end are an approximation for the use of the Srophé App only. These dates will not appear in the HTML view of the record, nor should human users consider them to be anything other than heuristic values to permit calculations. The dates are intentionally set to January 1 (the earliest possible date possible) because the actual date is unknown.

**Comment by davidamichelson** [comment]
And this issue https://github.com/srophe/srophe-app-data/issues/816

**Comment by dlschwartz** [comment]
We do not use the following and can delete them without consequence if we want to.

xmlns:xi="http://www.w3.org/2001/XInclude"
xmlns:svg="http://www.w3.org/2000/svg"
xmlns:math="http://www.w3.org/1998/Math/MathML"

**Comment by dlschwartz** [comment]
That said, if we got into drawing polygons in place data, we would likely need svg.

**Comment by dlschwartz** [comment]
I would clarify that we use @srophe:computed-start & @srophe:computed-end for making timelines (and, I believe, exclusively for making timelines). If another project didn't care about timelines they could drop this feature without consequence. Probably want to confirm with Winona on this though.

**Comment by dlschwartz** [comment]
In general, throughout the documentation I would recommend a two-space indent for each line. These indents are too big and decrease readability. I usually put code snippets into a simple text editor and adjust spacing before I upload them in markdown.

**Comment by dlschwartz** [comment]
Whenever possible, I would recommend using returns so that viewing code snippets requires minimal scrolling.

**Comment by dlschwartz** [comment]
Sorry, I think [this comment](https://github.com/srophe/srophe-app-data/issues/765#issuecomment-631700144) addresses what I was getting at in my [comment above](https://github.com/srophe/srophe-app-data/issues/765#issuecomment-632179195) about `@srophe:computed-start` & `@srophe:computed-end`. Nothing more needed there.

**Comment by davidamichelson** [comment]
Thanks @dlschwartz
