### ISSUE TITLE
Allow date attributes on Location and child elements of Location

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#804]
See issues #773 and #803 

Do we already allow this in the schema?

@dlschwartz we would like to allow att.datable and its cousins on Location and child elements of Location.

att.datable (@Calendar, @period)
att.datable.w3c (@when, @notBefore, @notAfter, @from, @to)
att.datable.iso (@when-iso, @notBefore-iso, @notAfter-iso, @from-iso, @to-iso)
att.datable.custom (@when-custom, @notBefore-custom, @notAfter-custom, @from-custom, @to-custom, @datingPoint, @datingMethod)

**Comment by dlschwartz** [comment]
@davidamichelson @wlpotter TEI P5 All already assigns `<bloc>`, `<country>`, `<district>`, `<offset>`, `<placeName>`, `<region>`,  and `<settlement>` to all of the datable attribute classes. 

What remains in our current schema as acceptable children of location are `<geo>` and `<measure>`. We could customize these and/or request changes to the TEI. There are certainly cases where changes over time to coordinates (point or polygon for a city) and distances ("20km outside a city" might end up inside that city at a later date).

When I look at our data, however, I can't imagine where we would want to temporally qualify anything other than an entire `<location>` element. That is the only thing we source. If a source or sources say different things about a place at different times it seems we would simply include a `<location>` element for each assertion, source it, and provide the desired datable attributes.

**Comment by davidamichelson** [comment]
@davidamichelson will add to the documentation that each location element is based on a separate source. So use multiple location based on @source, as a default the @source and @datable should go on the TEI:location

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson feel free to correct me if what I've written up here misses any of what we discussed. 

We want dates to appear on `<location>` but not on its children.

The following elements appear in our data only as children of `<location>`: `<bloc>`, `<country>`, `<district>`, `<offset>`, `<region>`, and `<settlement>`. Since we don't use them elsewhere, I will remove all of these elements from all four of the att.datable attribute classes listed above. 

We use `<placeName>` in many contexts and it might be desirable to have date attributes in some of those contexts. I will write a schematron rule for when `<placeName>` is used as a child of `<location>` indicating that a date should be applied to the parent `<location>` and not to the `<placeName>` element.
