### ISSUE TITLE
All notes must have an @type

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#843]
We need to update this one

```
<note>
used under a Creative Commons Attribution license
<ref target="http://creativecommons.org/licenses/by/3.0/"/>
</note>
```

to

```
<note type="license">
used under a Creative Commons Attribution license
<ref target="http://creativecommons.org/licenses/by/3.0/"/>
</note>
```

**Comment by davidamichelson** [comment]
@wlpotter Could you make this change to all records which have license/note please? Add note type="license"

**Comment by davidamichelson** [comment]
path is /TEI/teiHeader/fileDesc/publicationStmt/availability/licence/p/note

**Comment by wlpotter** [comment]
This has been changed in all data (on [this branch](https://github.com/srophe/srophe-app-data/tree/2019-May-Batch-Changes/)). 

Are there schema changes or documentation updates that are needed? I noticed that the schema is throwing an error on place records with this change because the value of `@type="license"` is not allowed.

**Comment by wlpotter** [comment]
@davidamichelson @dlschwartz Does this issue require schema or documentation changes? If not, we can go ahead and close it.

**Comment by dlschwartz** [comment]
@wlpotter the commit above should allow the changes to validate.

**Comment by wlpotter** [comment]
Great, the schema is working as intended.

@davidamichelson the documentation needs to be updated to reflect this change.

**Comment by davidamichelson** [comment]
Done
