### ISSUE TITLE
tei:revisionDesc status="uncorrected-draft"

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#848]
#https://github.com/srophe/srophe-app-data/issues/752 #https://github.com/srophe/srophe-app-data/issues/789

@wlpotter @davidamichelson we have `<revisionDesc status="uncorrected-draft">` on over 400 place records. This doesn't validate in the current schema. I'm assuming I should add this to the schema but wanted to confirm. Thanks.

**Comment by davidamichelson** [comment]
@wlpotter please change all to "draft"

**Comment by wlpotter** [comment]
I have updated the `@status` attribute of these records from "uncorrected-draft" to "draft". I believe this resolves any need for schema or documentation updates. 

"uncorrected-draft" was a temporary designation we used in the merging of dev into production, but we have since deprecated that usage in favor of the "draft" attribute value.
