### ISSUE TITLE
Personal religious affiliation factoids structure

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#892]
@dlschwartz @lunadine @Torabik I would be glad for your thoughts on this. Ideally we could model something that is relevant to the SPEAR factoid model in general, not just Usaybia. 

For Usaybia, I need to be able to create factoids about religious affiliation. Dan and I have talked previously about the fact that this is less relevant/more problematic for late antique sources, where the concept of "religion" is in question. For our 13th-cent. text, though, it is often the case that the author explicitly or implicitly labels someone as belonging to a religious community. 

There are two questions on this for the SPEAR family of factoid prosopography: how should the factoid be structured (i.e. which element should we use), and how should we use/adapt taxonomy terms? I'll deal with structure here and open another issue for taxonomy terms. 

### 1. Should we use faith, state, or another element?
For example, using state
```
<ab type="factoid" subtype="religious-affiliation" xml:id="factoid-1" resp="#ngibson">
    <idno type="URI">https://usaybia.net/factoid/12-1</idno>
    <listPerson>
        <person>
            <persName ref="https://usaybia.net/person/926"/>
            <state ana="http://syriaca.org/keyword/islam">
                <note type="desc">
                    <persName ref="https://usaybia.net/person/926">Ibn Abī Uṣaybiʿa</persName>
                    was affiliated with Islam.
                </note>
            </state>
        </person>
    </listPerson>
    ...
</ab>
```
or using faith
```
<ab type="factoid" subtype="religious-affiliation" xml:id="factoid-2" resp="#ngibson">
    <idno type="URI">https://usaybia.net/factoid/12-2</idno>
    <listPerson>
        <person>
            <persName ref="https://usaybia.net/person/926"/>
            <faith ana="http://syriaca.org/keyword/islam">
                <note type="desc">
                    <persName ref="https://usaybia.net/person/926">Ibn Abī Uṣaybiʿa</persName>
                    was affiliated with Islam.
                </note>
            </faith>
        </person>
    </listPerson>
...
</ab>
```
In the guidelines I don't see anything structurally (attributes, contained elements, etc) that seems to matter.  Faith would be the most obvious choice (and perhaps most predictable for interoperability), but it seems defined in a way that implies it has to do with beliefs more than communal affiliation https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-faith.html. State is very generic, but the examples include membership in the Beatles! https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-state.html  The affiliation element seems to be used in a strict sense of affiliation with an organization, so I don't think that's too relevant. 

@dlschwartz I don't know which attributes you're currently using to limit taxonomy keywords? Are there practical considerations here? I assume one could limit keywords to e.g. children of http://syriaca.org/keyword/buddhism on the basis of `ab/subtype='religious-affiliation'`? 

### 2. How should we indicate a conversion event? 
E.g., 
```
<ab type="factoid" subtype="event" xml:id="factoid-3" resp="#ngibson">
    <idno type="URI">https://usaybia.net/factoid/12-3</idno>
    <listEvent>
        <event ana="http://syriaca.org/keyword/islam http://syriaca.org/keyword/conversion">
            <desc>
                <persName ref="https://usaybia.net/person/139"/>
                <choice>
                    <reg>
                        <date notBefore="1160" notAfter="1170" calendar="#gregorian">Between 1160 and 1170</date>
                    </reg>
                    <orig>
                        <date notBefore="0555" notAfter="0566" calendar="#hijri">Between 555 and 566</date>
                    </orig>
                </choice>
                <persName ref="https://usaybia.net/person/139">Abū l-Barakāt al-Baghdādī</persName>
                became a Muslim.
            </desc>
        </event>
    </listEvent>
    <bibl type="urn">
        <ptr target="urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-ed-ara1:10.66"/>
        <citedRange unit="part">5</citedRange>
    </bibl>
</ab>
```
The above would provide us with a structured way of indicating conversion _to_ a religion. It would rely on other (dated) factoids to indicate the person's previous affiliation. This matches the way the source text usually speaks of conversion, as "became a Muslim" rather than "converted to Islam from X". But it means any previous affiliations would have to include a usually approximate end date that matches the conversion event date. I don't know of any way of linking state and event factoids, is there? 

The alternative would be to mention both the _from_ and _to_ affiliations in the conversion event, but I don't think of a way to do that without inventing a new structure, like a new type of relation or a specific structure within the desc. What do you think?

Thanks, would be really glad for your input.

Related: https://github.com/usaybia/usaybia-data/issues/92

**Comment by dlschwartz** [comment]
@nathangibson @lunadine @Torabik This is something I've avoided really digging into because it isn't super relevant to the period I'm working in. Things are so in flux during the 6th century that there really aren't categories to apply. I can see how it's critical for your material though Nathan. I think it's time to sort this out.

### Element
The proper element to use is a tricky issue. It seems that we should use `<faith>` since it is such a clear cut element in the TEI. However, you're right that it is rather narrowly defined as belief. It gets more complicated than this though. Read [13.3.1](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDPERSbp) of the Guidelines. Here they list "faith" as a `<trait>` alongside "sex or hair and eye colour, or cultural, such as ethnicity, and caste." Then they define `<trait>` as something "independent of the volition or action of the holder". To my mind this applies much better to "religion" than it does to "faith" which seems to require some volition. 

This leads me to think that `<state>` might be best [[link to guidelines](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-state.html)]. It is for "a description of some status or quality attributed to a person, place, or organization often at some specific time or for a specific date range." We currently use `<state>` for mental states and for sanctity (saints, etc.). We could add `<state type="religious-affiliation">.`

Have you thought about the possibilities for qualifying religious-affiliation? See the example of the `@type` attribute values suggested with `<faith>:` [https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-faith.html](url). We could use `@subtype` to define the nature of the religious affiliation. Unfortunately, we're already using `@ana` for the URL pointing to the religion in the taxonomy. If we wanted different types of religious affiliation to be in the taxonomy we would need to figure out how to point to those. I think `@subtype` should be sufficient though.

### Constraining Values
Yes, we can use `<ab subtype="religious-affiliation">` to constrain the value of whatever attribute we use here. That will be easy with one significant caveat. We don't have a keyword list to point to at the moment. Currently Syriaca.org has two divergent lists of religious affiliations. 

- The taxonomy contains insufficiently structured religions (i.e. the "Christianity" is currently encoded as a [skos:broadMatch](https://github.com/srophe/srophe-app-data/blob/master/data/subjects/tei/christianity.xml#L111) with "Religion," but so is something like "Holy Places". There is no way in the current taxonomy to point to specific religions. That is a goal but we just don't have it yet.) 
- The other challenge is that Syriaca.org also has the list of religions developed for the Gazetteer and it doesn't match the taxonomy (which was derived from CBSC). That list should be [at this link](https://syriaca.org/documentation/confessions.html) but it's not appearing. You can find it [at this link](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/confessions.xml) instead.

I would like one list of religions for Syriaca.org. It should exist in the taxonomy and we should probably update the Gazetteer to point to that LOD-compatible list rather than to our documentation page. 

In the short run, we could simply create a list of URIs that reconciles the taxonomy and the Gazetteer list and hard code that into the schema. Then, once we get the taxonomy sorted, we could redo the rules in the schema to point directly to the taxonomy list.

### Conversion
This is probably the hardest. You have to have a way to describe the fact that someone was affiliated with a religion even though you will often have the situation where you are not told about the event. But what to do when you do have a discussion of the event.

First of all, recall that the schema allows dates on `<state>`. You can always have two "religious-affiliation" factoids in which the dates appear as attributes on `<state>` (options are currently the W3C (Gregorian) dates using `@when`, `@notBefore`, `@notAfter`, `@from` and `@to`). If you want to include other calendars you can always do that in the `<note>`. 

I also do not know an easy way to link up states and events. I'm reluctant to make religious affiliation a relationship factoid. The clearest thing there would be a relationship between a person and an organization. That is not ideal since there are ways to "affiliate" that do not include membership in an organization. Moreover, the organization "the Catholic Church" isn't really the same thing in the 3rd century as it is in the 15th century. 

Unfortunately, I feel like it would get really difficult to manage a system of relation elements that could link any factoid to any other factoid. (We currently link between closely related events, but that's it.) We could certainly do that but it would get really complicated.

We can add a relationship to an event if the event creates a relationship (i.e. baptism or ordination). Should we allow states in a similar way? Where would it stop? I could imagine including: occupation, residence, education, etc. Maybe that's fine.

How important is it for things you want to be able to do that you can link these two types of data? Let's start there.

**Comment by nathangibson** [comment]
@dlschwartz Thank you so much!! Let me respond point-by-point. 

> ### Element
> 
> The proper element to use is a tricky issue. It seems that we should use `<faith>` since it is such a clear cut element in the TEI. However, you're right that it is rather narrowly defined as belief. It gets more complicated than this though. Read [13.3.1](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDPERSbp) of the Guidelines. Here they list "faith" as a `<trait>` alongside "sex or hair and eye colour, or cultural, such as ethnicity, and caste." Then they define `<trait>` as something "independent of the volition or action of the holder". To my mind this applies much better to "religion" than it does to "faith" which seems to require some volition.
> 
> This leads me to think that `<state>` might be best [[link to guidelines](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-state.html)]. It is for "a description of some status or quality attributed to a person, place, or organization often at some specific time or for a specific date range." We currently use `<state>` for mental states and for sanctity (saints, etc.). We could add `<state type="religious-affiliation">.`
> 
> Have you thought about the possibilities for qualifying religious-affiliation? See the example of the `@type` attribute values suggested with `<faith>:` [https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-faith.html](url). We could use `@subtype` to define the nature of the religious affiliation. Unfortunately, we're already using `@ana` for the URL pointing to the religion in the taxonomy. If we wanted different types of religious affiliation to be in the taxonomy we would need to figure out how to point to those. I think `@subtype` should be sufficient though.

I have also come to think that `state` is the best element, for similar reasons. I hadn't paid much attention to the `@type` values for faith, those are interesting. It is a bit similar to what I'm currently doing in person _entries_, which is to put `@evidence` combined with `@cert` on `<state type="religious-affiliation">`. So far the values I have for `@evidence` are 
- occupation
- descendant-name
- ancestor-name
- given-name
- nisba

I'm trying to envision how this would work with factoids. So far I've been assuming we would only record a religious affiliation factoid where a source explicitly labels someone with that affiliation. Otherwise, I would make some weighted inferences from processing factoids for occupations (priests, qadis, etc.), names, relationships, etc. So I'm not really sure we need a `@subtype` on state. What do you think?

**Comment by nathangibson** [comment]
> ### Constraining Values
> 
> Yes, we can use `<ab subtype="religious-affiliation">` to constrain the value of whatever attribute we use here. That will be easy with one significant caveat. We don't have a keyword list to point to at the moment. Currently Syriaca.org has two divergent lists of religious affiliations.
> 
>     * The taxonomy contains insufficiently structured religions (i.e. the "Christianity" is currently encoded as a [skos:broadMatch](https://github.com/srophe/srophe-app-data/blob/master/data/subjects/tei/christianity.xml#L111) with "Religion," but so is something like "Holy Places". There is no way in the current taxonomy to point to specific religions. That is a goal but we just don't have it yet.)
> 
>     * The other challenge is that Syriaca.org also has the list of religions developed for the Gazetteer and it doesn't match the taxonomy (which was derived from CBSC). That list should be [at this link](https://syriaca.org/documentation/confessions.html) but it's not appearing. You can find it [at this link](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/confessions.xml) instead.
> 
> 
> I would like one list of religions for Syriaca.org. It should exist in the taxonomy and we should probably update the Gazetteer to point to that LOD-compatible list rather than to our documentation page.
> 
> In the short run, we could simply create a list of URIs that reconciles the taxonomy and the Gazetteer list and hard code that into the schema. Then, once we get the taxonomy sorted, we could redo the rules in the schema to point directly to the taxonomy list.

@dlschwartz Constraining values would be nice at some point but it's not that critical. I would suggest we not wait for the lists to be perfect before we create religious affiliation factoids. So far we can pretty much find all the keywords we need in some form, and we can suggest new ones as needed. The only issue is that if the URIs change, we'll need to make sure our Usaybia data reflect those changes. (Regarding some problems with the current keywords, see #893).

**Comment by nathangibson** [comment]
> ### Conversion
> 
> This is probably the hardest. You have to have a way to describe the fact that someone was affiliated with a religion even though you will often have the situation where you are not told about the event. But what to do when you do have a discussion of the event.
> 
> First of all, recall that the schema allows dates on `<state>`. You can always have two "religious-affiliation" factoids in which the dates appear as attributes on `<state>` (options are currently the W3C (Gregorian) dates using `@when`, `@notBefore`, `@notAfter`, `@from` and `@to`). If you want to include other calendars you can always do that in the `<note>`.
> 
> I also do not know an easy way to link up states and events. I'm reluctant to make religious affiliation a relationship factoid. The clearest thing there would be a relationship between a person and an organization. That is not ideal since there are ways to "affiliate" that do not include membership in an organization. Moreover, the organization "the Catholic Church" isn't really the same thing in the 3rd century as it is in the 15th century.
> 
> Unfortunately, I feel like it would get really difficult to manage a system of relation elements that could link any factoid to any other factoid. (We currently link between closely related events, but that's it.) We could certainly do that but it would get really complicated.
> 
> We can add a relationship to an event if the event creates a relationship (i.e. baptism or ordination). Should we allow states in a similar way? Where would it stop? I could imagine including: occupation, residence, education, etc. Maybe that's fine.
> 
> How important is it for things you want to be able to do that you can link these two types of data? Let's start there.

Ultimately I don't think it's that important to link states and events in our case. I would think of the factoids as expressing various attestations of religious affiliation by the source, whether as a static label (state) or through conversion (event). Where possible, we'll try to include whatever dates can be inferred, especially in the case of conversion or conflicting attestations. So we'll want to query the factoids and get, e.g., "Abu al-Barakat was Jewish (date range)" (state) and "Abu al-Barakat became Muslim (date)" (event). From that we can infer what we need to. If the source mentions the person's previous religion, that could be a separate factoid. 

However, for the sake of clarity, should there be a "conversion to" event and, as a separate factoid, a "conversion from" event? Should these be separate keywords so that the event factoids can be properly queried? (I see that the taxonomy already has https://syriaca.org/keyword/apostasy but this might be with a different meaning.) 

My research questions have more to do with finding which persons were connected to which communities than with mapping a trajectory of affiliations for an individual. So if we can see that Abu al-Barakat was affiliated with both Jewish and Muslim communities, that is adequate. 

So is the [above example](https://github.com/srophe/srophe-app-data/issues/892#issue-813471193) of conversion adequate?

**Comment by nathangibson** [comment]
@dlschwartz here's an interesting possibility for conversion keywords: https://github.com/srophe/srophe-app-data/issues/893#issuecomment-899724902

**Comment by dlschwartz** [comment]
### Re: the element question
@nathangibson @lunadine I agree that tei:state is the best way to go. It might be best to leave qualifications or categorizations to individual research projects. Different research agendas and different source bases will need different qualifications. But let's keep discussing if need be.

**Comment by dlschwartz** [comment]
### Conversion
@nathangibson @lunadine I agree that we could use something like conversion-from and conversion-to. There would still be options though.

- `<event ana="http://syriaca.org/keyword/islam http://syriaca.org/keyword/conversion">`
- `<event ana="http://syriaca.org/keyword/islam http://syriaca.org/keyword/christianity http://syriaca.org/keyword/conversion">`
- `<event ana="http://syriaca.org/keyword/islam http://syriaca.org/keyword/christianity http://syriaca.org/keyword/conversion-from http://syriaca.org/keyword/conversion-to">`
- `<event ana="http://syriaca.org/keyword/islam http://syriaca.org/keyword/conversion-to">` along with a second factoid for the same event `<event ana="http://syriaca.org/keyword/christianity http://syriaca.org/keyword/conversion-from">` 

Depending what you want out of the data, each of these could be useful ways to encode the event. I don't think that the TEI will easily allow the use of a combination of attributes/values that would capture all of the complexity of conversion from one religious affiliation to another religious affiliation. I could imagine an XML schema that would facilitate this, but it would depart from the TEI.

I think the best bet would be to encode two events. Also recall that if you encoded these two events you would have the option of linking them with the `<relation ref="http://syriaca.org/keyword/same-event">` (paragraph 38 of [our article](https://oaktrust.library.tamu.edu/bitstream/handle/1969.1/192423/gibson-schwartz-torabi-modeling-factoid-prosopographyPRE-PRINT.pdf?sequence=1&isAllowed=y)). This is actually a really good use case for same-event. It is the same event but there are two distinct pieces of data you want to collect about that same event.

**Comment by dlschwartz** [comment]
@nathangibson @lunadine The above commit updates tei:state to include religious affiliation. Once we come up with a list (see #893) for religious affiliation keywords we can hard code that into the schema. And later when the taxonomy gets update we can draw directly from that.

**Comment by dlschwartz** [comment]
@nathangibson @lunadine two changes in the above commit:

- I had forgotten to add religious affiliation as a subtype option on tei:ab. I've done that.
- Also, I remembered that elsewhere we use camel case for these attribute values. I've changed from "religious-affiliation" to "religiousAffiliation" to maintain consistency.

**Comment by nathangibson** [comment]
@dlschwartz Excellent, thank you so much!!
