### ISSUE TITLE
Possible problems with merged data

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#895]
@jsaintlauren and I recently found a record http://syriaca.org/person/784 that contains data for two separate people, Theodosius, d. 566 and Theodore, fl. 649-657. Looking at the change log in the TEI file, it looks like the source of the problem might be data merges from May 2016. The speculation is that there was a saint record based on Fiey using person/784 and an author record using person/784. We think a script was used to merge these two records without realizing that they were two different people. 

We have used a branch to mark out, but not deleted, the portions of this record that pertain to Theodore. (This record should be about Theodosius.) https://github.com/srophe/srophe-app-data/commit/e1114eebc3d17d159c11dc987bb6717edd66d493 

- We need to create a Theodore record which I believe Jeanne-Nicole will do.
- Also, these merges should be researched to see if the problem is more widespread than this one record. Perhaps @wlpotter could work on this? (Welcome back Will! Looking forward to chatting soon.)

**Comment by dlschwartz** [comment]
And one more thing. Do we really need to have a separate file in the person folder for saints or does it make most sense to put all persons into one folder?

**Comment by nathangibson** [comment]
@dlschwartz @jsaintlauren I think I can clarify a little bit ... I probably did the merge using some version of this script: https://github.com/srophe/srophe-xQueries/blob/master/merge-persons.xql

Your theory that there was a saint an author with the same URI aligns with the changelog note at https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/784.xml#L206

My apologies, this was probably my bad! 

In general the saints and authors should not have had overlapping URIs, so I'm hopeful that this was just a one-off problem.

**Comment by dlschwartz** [comment]
Thanks @nathangibson. No blame assigned or apology needed. I didn't want to bother you with this but I'm glad to hear that you are confident that this likely isn't a wider problem. Knowing the specific script that was likely used is also helpful. Thanks!

**Comment by wlpotter** [comment]
@nathangibson thanks for this info! It helps to know that the script generates that changelog note. @dlschwartz @jsaintlauren I can check the rest of persons data and flag any records that have that changelog note. Hopefully it is an isolated issue, but this should give us a list of any affected records.

**Comment by dlschwartz** [comment]
Great. Thanks @wlpotter

**Comment by wlpotter** [comment]
Searching for that changelog note returned 67 person records...It may be that some of these merges were intended (a spot check of, e.g., [person 50, John of Tella](https://syriaca.org/person/50) doesn't seem to have merge issues). We did something similar with place data in the Beth Qatraye Gazetteer (using a version of @nathangibson's script) since we had multiple records for the same place but with different bits of data. 

I'm not sure if there's a way to narrow it down any more, but here's the list of URIs:

https://syriaca.org/person/9
https://syriaca.org/person/10
https://syriaca.org/person/13
https://syriaca.org/person/25
https://syriaca.org/person/26
https://syriaca.org/person/42
https://syriaca.org/person/44
https://syriaca.org/person/50
https://syriaca.org/person/51
https://syriaca.org/person/52
https://syriaca.org/person/57
https://syriaca.org/person/67
https://syriaca.org/person/69
https://syriaca.org/person/75
https://syriaca.org/person/93
https://syriaca.org/person/106
https://syriaca.org/person/113
https://syriaca.org/person/122
https://syriaca.org/person/126
https://syriaca.org/person/139
https://syriaca.org/person/145
https://syriaca.org/person/173
https://syriaca.org/person/209
https://syriaca.org/person/212
https://syriaca.org/person/227
https://syriaca.org/person/239
https://syriaca.org/person/271
https://syriaca.org/person/306
https://syriaca.org/person/320
https://syriaca.org/person/321
https://syriaca.org/person/326
https://syriaca.org/person/354
https://syriaca.org/person/356
https://syriaca.org/person/360
https://syriaca.org/person/366
https://syriaca.org/person/376
https://syriaca.org/person/430
https://syriaca.org/person/451
https://syriaca.org/person/477
https://syriaca.org/person/511
https://syriaca.org/person/513
https://syriaca.org/person/530
https://syriaca.org/person/544
https://syriaca.org/person/550
https://syriaca.org/person/561
https://syriaca.org/person/573
https://syriaca.org/person/624
https://syriaca.org/person/628
https://syriaca.org/person/637
https://syriaca.org/person/650
https://syriaca.org/person/655
https://syriaca.org/person/680
https://syriaca.org/person/709
https://syriaca.org/person/721
https://syriaca.org/person/744
https://syriaca.org/person/779
https://syriaca.org/person/780
https://syriaca.org/person/784
https://syriaca.org/person/785
https://syriaca.org/person/809
https://syriaca.org/person/811
https://syriaca.org/person/821
https://syriaca.org/person/825
https://syriaca.org/person/826
https://syriaca.org/person/834
https://syriaca.org/person/856
https://syriaca.org/person/883

**Comment by dlschwartz** [comment]
Thanks @wlpotter. I spot checked about half of these and didn't see strange combinations of name variants or dates and it looks like the works commemorating them correspond to the right person. Let's consider this one closed. Thanks!
