### ISSUE TITLE
Deprecated and redirect URIs throwing app error

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#909]
https://syriaca.org/person/44 is an example of a record with duplicated URIs.

**Comment by dlschwartz** [comment]
Found another here too. https://syriaca.org/person/2432

**Comment by wlpotter** [comment]
@dlschwartz Here's a third https://syriaca.org/person/8

I can compile a list of these, I believe, by querying the count of idnos in the tei:publicationStmt. I'd like to double check with everyone on how to handle new cases where we want to deprecate records because we've merged persons (see, e.g. #916). 

But I think we also need an app issue as it currently doesn't seem to be handling the redirects correctly?

**Comment by nathangibson** [comment]
Hi @wlpotter , forgive me, I'm not sure how much of the background you know. The merging and deprecating procedure was one we worked out a few years ago, documented (hopefully still accurately) here: https://github.com/srophe/srophe-app-data/wiki/Deprecated-Records

If this procedure is followed, the app _should_ handle redirects correctly, but maybe something has changed since then. 

You already know the merge and deprecate script right?

**Comment by wlpotter** [comment]
@nathangibson thank you for this! It will help in sorting out whether we have an app or data issue. This issue (whose name is probably misleading...) came about because we found instances of the app throwing cardinality errors on the tei:idno elements in `//tei:publicationStmt`, which I believe is because of the deprecated tei:idno. 

I will verify that the records throwing that error follow [the documentation you linked](https://github.com/srophe/srophe-app-data/wiki/Deprecated-Records). If they do, I will make an app-issue; otherwise, I will update the data to make sure the app can handle the redirect.

**Comment by nathangibson** [comment]
@wlpotter Sounds perfect, thanks :-)

**Comment by wlpotter** [comment]
These were fixed with the updated srophe image
